"""empty message

Revision ID: 295d39dccd2d
Revises: 
Create Date: 2020-07-23 22:31:36.154292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295d39dccd2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_title', sa.String(length=200), nullable=True),
    sa.Column('post_subtitle', sa.String(length=300), nullable=True),
    sa.Column('post_content', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('post_was_edited', sa.Boolean(), nullable=True),
    sa.Column('post_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer_user_id', sa.Integer(), nullable=False),
    sa.Column('writer_about_me', sa.String(length=200), nullable=True),
    sa.Column('writer_short_summary', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['writer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writer')
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
