"""empty message

Revision ID: 44119139dc9a
Revises: 8a59829c27ae
Create Date: 2020-11-11 19:05:14.378301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44119139dc9a'
down_revision = '8a59829c27ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__ARTICLE__AUTHOR__36B12243', 'ARTICLE', type_='foreignkey')
    op.create_foreign_key(None, 'ARTICLE', 'USER', ['AUTHOR'], ['id'])
    op.add_column('USER', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('USER', 'ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False, mssql_identity_start=1, mssql_identity_increment=1))
    op.drop_column('USER', 'id')
    op.drop_constraint(None, 'ARTICLE', type_='foreignkey')
    op.create_foreign_key('FK__ARTICLE__AUTHOR__36B12243', 'ARTICLE', 'USER', ['AUTHOR'], ['ID'])
    # ### end Alembic commands ###
