"""empty message

Revision ID: c31c6281f4c5
Revises: 702aa9afe449
Create Date: 2020-08-02 21:03:10.263778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31c6281f4c5'
down_revision = '702aa9afe449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('user')
    op.create_table('user',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(150)),
        sa.Column('email', sa.String(120), nullable=False),
        sa.Column('password', sa.String(200), nullable=False),
        sa.Column('about', sa.String(200)),
        sa.Column('subtitle', sa.String(40)),
        sa.Column('website', sa.String(200))
    )
    # op.add_column('user', sa.Column('about', sa.String(length=200), nullable=True))
    # op.add_column('user', sa.Column('email', sa.String(length=120), nullable=False))
    # op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    # op.add_column('user', sa.Column('password', sa.String(length=200), nullable=False))
    # op.add_column('user', sa.Column('subtitle', sa.String(length=40), nullable=True))
    # op.add_column('user', sa.Column('website', sa.String(length=200), nullable=True))
    # op.drop_column('user', 'user_password')
    # op.drop_column('user', 'user_email')
    # op.drop_column('user', 'user_subtitle')
    # op.drop_column('user', 'user_about')
    # op.drop_column('user', 'user_website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_website', sa.VARCHAR(length=200), nullable=True))
    op.add_column('user', sa.Column('user_about', sa.VARCHAR(length=200), nullable=True))
    op.add_column('user', sa.Column('user_subtitle', sa.VARCHAR(length=40), nullable=True))
    op.add_column('user', sa.Column('user_email', sa.VARCHAR(length=120), nullable=False))
    op.add_column('user', sa.Column('user_password', sa.VARCHAR(length=200), nullable=False))
    op.drop_column('user', 'website')
    op.drop_column('user', 'subtitle')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
