"""post table v1

Revision ID: ed95ef6ff0b6
Revises: 
Create Date: 2020-04-22 19:17:22.290606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed95ef6ff0b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_title', sa.String(length=200), nullable=True),
    sa.Column('post_subtitle', sa.String(length=300), nullable=True),
    sa.Column('post_content', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('post_was_edited', sa.Boolean(), nullable=True),
    sa.Column('post_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
